services:
  balances-app:
    build: ./balances-service
    environment:
      DB_CONNECTION: mysql
      DB_HOST: balances-mysql
      DB_PORT: 3306
      DB_DATABASE: balances
      DB_USERNAME: root
      DB_PASSWORD: your_mysql_root_password
    depends_on:
      - balances-mysql